### ISSUE TITLE
[SETUP] 프로젝트 초기 설정

### ISSUE THREAD

**Issue by marso34** [marso34/ytt-medicine-vending-machine#1]
## 내용
- 프로젝트 초기 세팅
- 네이밍 규칙
   - BE: Back-End
   - FE: Android Application
   - ES: Embedded System

## To-Do
- [x] Issues Template 생성
- [x] PR Template 생성
- [x] 초기 디렉토리 생성
   - [x] #3
   - [x] #4
   - [x] #7
