### ISSUE TITLE
[FEAT] 자판기 entity 생성 : BE

### ISSUE THREAD

**Issue by marso34** [marso34/ytt-medicine-vending-machine#13]
## 내용(Describe the Feature)
자판기 개발을 위한 entity 생성

## To-Do
- [x] DB GIS를 위한 의존성 추가 
- [x] 자판기 entity 생성
- [x] 자판기 repository 생성
