### ISSUE TITLE
[FEAT] 자판기 조회, 생성 등 로직 구현 : BE

### ISSUE THREAD

**Issue by marso34** [marso34/ytt-medicine-vending-machine#18]
## 내용(Describe the Feature)
자판기 조회, 생성 등 로직 구현

## To-Do
- [x] 자판기 DTO 생성
- [x] 자판기 Service 생성
- [x] 자판기 Controller 생성
