### ISSUE TITLE
[FEAT] Swagger 간편화 : BE

### ISSUE THREAD

**Issue by marso34** [marso34/ytt-medicine-vending-machine#28]
## 내용(Describe the Feature)
Custom Annotation을 활용해서 Swagger 간편하게 사용할 수 있게 구현 및 응답 dto 통일

## To-Do
- [x] Custom Annotation 생성
- [x] Controller에 Custom Annotation 적용
- [x] 공통 ResponseDto 생성
