### ISSUE TITLE
[REFACTOR] 유저 회원가입/로그인 리팩토링 : BE

### ISSUE THREAD

**Issue by Eeeegarden** [marso34/ytt-medicine-vending-machine#51]
## 내용
User 로그인/회원가입 #49 리뷰에 따른 코드 리팩토링

## To-Do
- [x] 인스턴스 책임분리 : User 인스턴스 생성
- [x] Swagger 적용 : UserController
- [x] 기능 추가 : 유저 정보 토대로 서버에 저장된 Refresh 삭제
