### ISSUE TITLE
[FEAT] 로그인/회원가입 개발 : FE

### ISSUE THREAD

**Issue by tpdlshdmlrkfmcla** [marso34/ytt-medicine-vending-machine#61]
## 내용(Describe the Feature)
크게는 로그인/회원가입 단 개발

## To-Do
- [x] 로그인/회원가입 - viewModel 처리;
   - [x] 헤더에 있는 토큰을 암호화해서 저장;
   - [x] 레트로핏 보낼 때 토큰 담아서 보낼 수 있게 설정;
