### ISSUE TITLE
[FEAT] 약 목록 페이지 추가 : FE

### ISSUE THREAD

**Issue by tpdlshdmlrkfmcla** [marso34/ytt-medicine-vending-machine#78]
## 내용(Describe the Feature)
서버에서 약 데이터를 받아서 목록을 띄우고 해당 약 선택 시 약 상세페이지로 이동후 상세페이지에서 주문하기 버튼을 클릭하도록 페이지를 구성한다.

## To-Do
- [x] 서버에서 약 데이터를 받아서 리스트 형태로 생성
- [x] 약을 선택한 후 나오는 약 상세 페이지 생성
- [x] 약 상세 페이지에서 주문하기 기능 구현
