### ISSUE TITLE
[FEAT] 자판기 관리 기능 : BE

### ISSUE THREAD

**Issue by marso34** [marso34/ytt-medicine-vending-machine#91]
## 내용(Describe the Feature)
- 자판기 등록, 상태 변경, 약 추가・변경, 입고 등 기능 구현
- 기존 안드로이드와의 통신에서 자판기 통신 추가
  - 자판기 관리 과정을 DB에 저장하는 것만이 아니라 자판기에도 전달할 수 있도록 구현

## To-Do
- [ ] 자판기
  - [x] 자판기 등록 과정
  - [x] 자판기 상태 변경
  - [ ] 자판기에 등록된 약 변경
  - [x] 자판기 관리자
- [ ] 약 추가 과정
  - Open API 가져오는 과정 최적화
- [x] 입고 로직
