### ISSUE TITLE
[REFACTOR] 주문 동시성 제어 수정 : BE

### ISSUE THREAD

**Issue by marso34** [marso34/ytt-medicine-vending-machine#92]
## 내용(Describe the Feature)
주문 동시성 제어 코드 수정 및 자판기 내 주문 추가

## To-Do
- [x] 동시성 제어 수정
- [x] 자판기에서 직접 주문 처리
- [x] 주문 내역 정렬 추가
